version: '3.7'
services:
  db:
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306 
    restart: unless-stopped
    volumes:
      -  ocp11-dbmysql:/var/lib/postgresql/data
    environment:
      MYSQL_ROOT_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  ocp11-dbmysql:
    driver: local

